import React, { useState, useEffect, useRef } from 'react';
import { FileText, Copy, Download, Trash2, CheckCircle2, AlertCircle } from 'lucide-react';
import type { SelectedStandardForTender } from '../types';
import html2pdf from 'html2pdf.js';

export default function TenderTemplate() {
  const [selectedStandards, setSelectedStandards] = useState<SelectedStandardForTender[]>([]);
  const [copied, setCopied] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    loadStandards();
  }, []);

  const loadStandards = () => {
    const stored = localStorage.getItem('spectra_tender_standards');
    if (stored) {
      try {
        setSelectedStandards(JSON.parse(stored));
      } catch (e) {
        console.error(e);
      }
    }
  };

  const clearTender = () => {
    if (confirm('Are you sure you want to clear the current tender?')) {
      localStorage.removeItem('spectra_tender_standards');
      setSelectedStandards([]);
    }
  };

  const removeStandard = (isNumber: string) => {
    const newList = selectedStandards.filter(s => s.standard.isNumber !== isNumber);
    localStorage.setItem('spectra_tender_standards', JSON.stringify(newList));
    setSelectedStandards(newList);
  };

  const handleCopy = () => {
    if (contentRef.current) {
      navigator.clipboard.writeText(contentRef.current.innerText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExport = () => {
    if (contentRef.current) {
      const opt = {
        margin:       1,
        filename:     'SpectraIS_Generated_Tender.pdf',
        image:        { type: 'jpeg' as const, quality: 0.98 },
        html2canvas:  { scale: 2 },
        jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' as const }
      };
      html2pdf().set(opt).from(contentRef.current).save();
    }
  };

  return (
    <div className="p-8 max-w-4xl mx-auto w-full h-full overflow-y-auto">
      <header className="mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-bold text-slate-800">Tender Builder</h1>
          <p className="text-slate-500 mt-2 flex items-center gap-2 text-sm">
            <span className="px-2 py-0.5 bg-indigo-100 text-indigo-700 rounded text-[10px] font-bold uppercase tracking-wider">Auto-Generated</span>
            Based on AI-verified analysis
          </p>
        </div>
        <button onClick={clearTender} className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold text-red-600 hover:bg-red-50 border border-red-200 rounded uppercase tracking-wider transition-colors">
          <Trash2 className="w-4 h-4" /> Clear All
        </button>
      </header>

      {selectedStandards.length === 0 ? (
        <div className="bg-slate-50 p-12 rounded-xl border border-slate-200 text-center flex flex-col items-center justify-center">
          <FileText className="w-16 h-16 text-slate-300 mb-4" />
          <h2 className="text-xl font-bold text-slate-700 mb-2">Tender is Empty</h2>
          <p className="text-slate-500 mb-6 max-w-md">You haven't added any verified standards to the tender yet. Go to the Analyze Tender page and click "Add to Tender" on the recommendations.</p>
        </div>
      ) : (
        <div className="bg-white p-8 rounded-xl border border-slate-200 shadow-sm relative">
          <div className="flex justify-between items-center mb-8 border-b border-slate-200 pb-4">
            <h2 className="text-xl font-bold text-slate-800">Section 6: Technical Specifications</h2>
            <div className="flex gap-3">
              <button onClick={handleCopy} className="flex items-center gap-2 text-xs text-slate-600 hover:text-indigo-600 font-bold uppercase tracking-wider px-3 py-1.5 rounded border border-slate-200 bg-slate-50 hover:bg-slate-100 transition-colors">
                {copied ? <CheckCircle2 className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />} {copied ? 'Copied!' : 'Copy'}
              </button>
              <button onClick={handleExport} className="flex items-center gap-2 text-xs text-white bg-indigo-600 hover:bg-indigo-700 font-bold uppercase tracking-wider px-3 py-1.5 rounded border border-indigo-700 transition-colors">
                <Download className="w-4 h-4" /> Export PDF
              </button>
            </div>
          </div>

          <div ref={contentRef} className="prose max-w-none text-slate-700 p-4 bg-white">
            <div className="mb-8 pb-4 border-b-2 border-slate-800">
              <h1 className="text-2xl font-black text-slate-900 mb-1 uppercase tracking-tight">TECHNICAL SPECIFICATIONS</h1>
              <p className="text-sm font-bold text-slate-500 uppercase tracking-widest">Document Generated by SpectraIS</p>
            </div>

            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-3 uppercase tracking-wider border-b border-slate-200 pb-2">1. Scope of Work</h3>
            <p className="mb-6">This specification covers the requirements for the supply, delivery, and testing of materials as per the following verified Indian Standards. All materials shall strictly conform to the latest revisions and amendments of the respective standards listed below.</p>

            <h3 className="text-lg font-bold text-slate-800 mt-6 mb-3 uppercase tracking-wider border-b border-slate-200 pb-2">2. Applicable Standards & Material Requirements</h3>
            
            {selectedStandards.map((item, index) => (
              <div key={item.standard.isNumber} className="mb-6 relative group">
                <button 
                  onClick={() => removeStandard(item.standard.isNumber)}
                  className="absolute -right-4 top-0 p-1 text-slate-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                  title="Remove from Tender"
                >
                  <Trash2 className="w-4 h-4" />
                </button>
                <h4 className="text-md font-bold text-slate-900 mb-2">2.{index + 1} {item.standard.productCategory}</h4>
                <div className="pl-4 border-l-2 border-indigo-200 space-y-2">
                  <p><strong>2.{index + 1}.1 Material:</strong> {item.standard.title}</p>
                  <p><strong>2.{index + 1}.2 Applicable Standard:</strong> The material shall strictly conform to <span className="font-bold font-mono bg-slate-100 px-1 py-0.5 rounded text-indigo-700">{item.standard.isNumber}:{item.standard.year}</span> (including all latest amendments).</p>
                  
                  {item.standard.status === 'SUPERSEDED' || item.standard.status === 'WITHDRAWN' ? (
                    <div className="bg-red-50 border border-red-200 p-2 my-2 rounded text-red-700 text-xs flex items-start gap-2">
                      <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
                      <div>
                        <strong>WARNING:</strong> This standard is marked as {item.standard.status}. 
                        {item.standard.relationships.filter(r => r.type === 'SUPERSEDED_BY').length > 0 && (
                          <span> Please refer to {item.standard.relationships.find(r => r.type === 'SUPERSEDED_BY')?.targetIsNumber} instead.</span>
                        )}
                      </div>
                    </div>
                  ) : null}

                  {item.standard.relationships.filter(r => r.type === 'TEST_METHOD').length > 0 && (
                    <p><strong>2.{index + 1}.3 Testing Methods:</strong> Testing shall be conducted in accordance with: {item.standard.relationships.filter(r => r.type === 'TEST_METHOD').map(r => r.targetIsNumber).join(', ')}.</p>
                  )}
                  
                  <p><strong>2.{index + 1}.4 Certification:</strong> {item.standard.certificationInformation}</p>
                </div>
              </div>
            ))}

            <h3 className="text-lg font-bold text-slate-800 mt-8 mb-3 uppercase tracking-wider border-b border-slate-200 pb-2">3. Quality Assurance</h3>
            <p>The contractor must submit test reports from a NABL accredited laboratory prior to dispatch. Materials arriving on site without proper BIS certification marks (where mandatory) or without conforming to the above specifications will be summarily rejected.</p>
          </div>
        </div>
      )}
    </div>
  );
}
